FROM postgres:15.6-bookworm

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        postgresql-15-postgis-3 \
        postgresql-15-postgis-3-scripts \
        postgresql-15-pgvector \
    && rm -rf /var/lib/apt/lists/*
